### ISSUE TITLE
how to configure to log on rank 0 only?

### ISSUE THREAD

**Issue by stas00** [NVIDIA/dllogger#9]
This same question at NVIDIA/NeMo project https://github.com/NVIDIA/NeMo/issues/7495 sent me here, but I don't see anything that will allow NeMo to tell Dllogger to log only on a given rank.

I proposed here https://github.com/NVIDIA/NeMo/issues/7495#issuecomment-1734433721 that NeMo handles that on their side, but I thought it would be good to have a joined conversation to see who ideally should be handling that.

If my proposal seems to be correct by design is it possible to document that on Dllogger side so there is no confusion about what's by design and what's just missing and will be implemented.

I currently use 512 gpus and end up with 512 identical log entries with Nemo/Dllogger so as you can imagine this is not what is needed.

Thank you!

**Comment by jan-golda** [comment]
Hi @stas00
Figuring out the current rank is not a trivial task. Each DL framework and scheduler handles it slightly differently.

Since DLLogger was designed to be a lightweight logging tool, that can be used to standardise the format across different frameworks, it leaves the complexity of concurrency management to the app that uses it.

As you can see in the [Deep Learning Examples](https://github.com/NVIDIA/DeepLearningExamples) repository each model handles it slightly differently, usually behind some version of `if` statement.

For example nnUNet uses `pytorch_lightning.utilities.rank_zero_only`:
https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Segmentation/nnUNet/utils/logger.py

As such, we do not have plans to support rank-based logging in DLLogger.

**Comment by stas00** [comment]
Thanks a lot for confirming that, Jan. So now hopefully NeMo will know to take charge of this issue.
